AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/iex-ruby-client.rb"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

inherit_from: .rubocop_todo.yml
