require_relative 'resources/resource'
require_relative 'resources/quote'
require_relative 'resources/company'
require_relative 'resources/price'
require_relative 'resources/news'
require_relative 'resources/chart'
require_relative 'resources/ohlc'
require_relative 'resources/logo'
